[package]
# Semantic Versioning is used: https://semver.org/
version = "1.0.0-beta.5"
authors = ["NVIDIA"]
title = "Warp Core"
description="The core Warp Python module"
readme  = "docs/README.md"
repository="https://github.com/nvidia/warp"
category = "core"
keywords = ["warp", "simulation"]
changelog="docs/CHANGELOG.md"

preview_image = "data/preview.png"
icon = "data/icon.png"

# Watch files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.py"]

# Core language module
[[python.module]]
name = "warp"
path = "."
public = true

[[python.module]]
name = "omni.warp.core"

# Kit testing flags
[[test]]
pyCoverageOmit = [
    "warp/stubs.py",
    "warp/jax.py",
    "warp/torch.py",
    "warp/build.py",
    "warp/build_dll.py",
    "warp/sim/**",
    "warp/render/**",
    "warp/optim/**",
    "warp/fem/**",
    "warp/thirdparty/**",
    "warp/tests/**"
]
pyCoverageThreshold = 40
timeout = 900
